import { sora, inter, work_sans } from "@/app/fonts";
import "@/app/globals.css";
import type { Metadata } from "next";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Save Recording",
  description: "Generated by create next app",
};

export default function VideoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className={sora.className}>
      <div className="relative min-h-screen">
        <Nav />
        {children}
        <Footer />
      </div>
    </section>
  );
}
