import { sora, inter, work_sans } from "@/app/fonts";
import "@/app/globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Recordings",
  description: "Generated by create next app",
};

export default function VideoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className={sora.className}>
      <div className="relative min-h-screen">
        <nav className="sticky w-full z-50 top-0 left-0 bg-white shadow-md">
          <div className="flex justify-between max-w-7xl mx-auto items-center w-full h-full px-4 py-3">
            <Link
              href="/"
              className="flex gap-2 justify-center items-center focus:outline-none focus-visible:ring-4 ring-neutral-600 rounded-sm ring-offset-4 hover:opacity-75 transition-opacity"
            >
              <Image
                src="/logo.svg"
                alt="HelpMeOut Logo"
                width={40}
                height={40}
                className="object-contain"
              />
              <p
                className={`${inter.className}text-2xl font-semibold tracking-wide text-primary-dark`}
              >
                HelpMeOut
              </p>
            </Link>

            <div className="flex justify-between items-center gap-1">
              <Image
                src="/avatar.svg"
                alt="avatar image"
                width={35}
                height={35}
                className="object-contain"
              />
              <p
                className={`${work_sans.className}text-base font-normal  text-primary-grey`}
              >
                John Mark
              </p>
              <Image
                src="/arrow-down.svg"
                alt="arrow-down"
                width={24}
                height={24}
                className="object-contain"
              />
            </div>
          </div>
        </nav>
        {children}
      </div>
    </section>
  );
}
